/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import type {
  ApiChangePasswordRequest,
  ApiLoginRequest,
  ApiRegisterRequest,
  ApiTokenResponse,
  ApiUpdateUserRequest,
  ApiUserResponse,
  ChangePassword200,
  RefreshTokenBody,
  VerifyTokenBody,
} from ".././model";

import { customInstance } from "../../../lib/axios-instance";

/**
 * Authenticate user and return JWT tokens
 * @summary Login user
 */
export const login = (apiLoginRequest: ApiLoginRequest) => {
  return customInstance<ApiTokenResponse>({
    url: `/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: apiLoginRequest,
  });
};
/**
 * Get information about the currently authenticated user
 * @summary Get current user
 */
export const getCurrentUser = () => {
  return customInstance<ApiUserResponse>({ url: `/me`, method: "GET" });
};
/**
 * Update information about the currently authenticated user
 * @summary Update current user
 */
export const updateCurrentUser = (
  apiUpdateUserRequest: ApiUpdateUserRequest,
) => {
  return customInstance<ApiUserResponse>({
    url: `/me`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: apiUpdateUserRequest,
  });
};
/**
 * Change password for the currently authenticated user
 * @summary Change password
 */
export const changePassword = (
  apiChangePasswordRequest: ApiChangePasswordRequest,
) => {
  return customInstance<ChangePassword200>({
    url: `/me/password`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: apiChangePasswordRequest,
  });
};
/**
 * Use refresh token to get a new access token
 * @summary Refresh access token
 */
export const refreshToken = (refreshTokenBody: RefreshTokenBody) => {
  return customInstance<ApiTokenResponse>({
    url: `/refresh`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: refreshTokenBody,
  });
};
/**
 * Register a new user account
 * @summary Register a new user
 */
export const register = (apiRegisterRequest: ApiRegisterRequest) => {
  return customInstance<ApiUserResponse>({
    url: `/register`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: apiRegisterRequest,
  });
};
/**
 * Verify a JWT token and return user information
 * @summary Verify JWT token
 */
export const verifyToken = (verifyTokenBody: VerifyTokenBody) => {
  return customInstance<ApiUserResponse>({
    url: `/verify`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: verifyTokenBody,
  });
};
export type LoginResult = NonNullable<Awaited<ReturnType<typeof login>>>;
export type GetCurrentUserResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type UpdateCurrentUserResult = NonNullable<
  Awaited<ReturnType<typeof updateCurrentUser>>
>;
export type ChangePasswordResult = NonNullable<
  Awaited<ReturnType<typeof changePassword>>
>;
export type RefreshTokenResult = NonNullable<
  Awaited<ReturnType<typeof refreshToken>>
>;
export type RegisterResult = NonNullable<Awaited<ReturnType<typeof register>>>;
export type VerifyTokenResult = NonNullable<
  Awaited<ReturnType<typeof verifyToken>>
>;
