/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type {
  ApiTimeSlotResponse,
  TimeSlotsList200,
  TimeSlotsListParams,
} from ".././model";

import { sporedInstance } from "../../../lib/spored-instance";

/**
 * List time slots
 * @summary List time slots
 */
export const timeSlotsList = (
  theaterID: string,
  roomID: string,
  params?: TimeSlotsListParams,
) => {
  return sporedInstance<TimeSlotsList200>({
    url: `/theaters/${theaterID}/rooms/${roomID}/timeslots`,
    method: "GET",
    params,
  });
};
/**
 * Show time slot
 * @summary Show time slot
 */
export const timeSlotsShow = (
  theaterID: string,
  roomID: string,
  timeSlotID: string,
) => {
  return sporedInstance<ApiTimeSlotResponse>({
    url: `/theaters/${theaterID}/rooms/${roomID}/timeslots/${timeSlotID}`,
    method: "GET",
  });
};
export type TimeSlotsListResult = NonNullable<
  Awaited<ReturnType<typeof timeSlotsList>>
>;
export type TimeSlotsShowResult = NonNullable<
  Awaited<ReturnType<typeof timeSlotsShow>>
>;
