/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type {
  ApiTheaterRequestBody,
  ApiTheaterResponse,
  TheatersList200,
  TheatersListParams,
} from ".././model";

import { sporedInstance } from "../../../lib/spored-instance";

/**
 * List theaters
 * @summary List theaters
 */
export const theatersList = (params?: TheatersListParams) => {
  return sporedInstance<TheatersList200>({
    url: `/theaters`,
    method: "GET",
    params,
  });
};
/**
 * Create theater
 * @summary Create theater
 */
export const theatersCreate = (
  apiTheaterRequestBody: ApiTheaterRequestBody,
) => {
  return sporedInstance<ApiTheaterResponse>({
    url: `/theaters`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: apiTheaterRequestBody,
  });
};
/**
 * Delete theater
 * @summary Delete theater
 */
export const theatersDelete = (theaterID: string) => {
  return sporedInstance<void>({
    url: `/theaters/${theaterID}`,
    method: "DELETE",
  });
};
/**
 * Show theater
 * @summary Show theater
 */
export const theatersShow = (theaterID: string) => {
  return sporedInstance<ApiTheaterResponse>({
    url: `/theaters/${theaterID}`,
    method: "GET",
  });
};
/**
 * Update theater
 * @summary Update theater
 */
export const theatersUpdate = (
  theaterID: string,
  apiTheaterRequestBody: ApiTheaterRequestBody,
) => {
  return sporedInstance<ApiTheaterResponse>({
    url: `/theaters/${theaterID}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: apiTheaterRequestBody,
  });
};
export type TheatersListResult = NonNullable<
  Awaited<ReturnType<typeof theatersList>>
>;
export type TheatersCreateResult = NonNullable<
  Awaited<ReturnType<typeof theatersCreate>>
>;
export type TheatersDeleteResult = NonNullable<
  Awaited<ReturnType<typeof theatersDelete>>
>;
export type TheatersShowResult = NonNullable<
  Awaited<ReturnType<typeof theatersShow>>
>;
export type TheatersUpdateResult = NonNullable<
  Awaited<ReturnType<typeof theatersUpdate>>
>;
