/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type {
  ApiPurchaseRequestBody,
  ApiPurchaseResponse,
  PurchasesList200,
  PurchasesListParams,
} from ".././model";

import { nakupInstance } from "../../../lib/nakup-instance";

/**
 * List purchases
 * @summary List purchases
 */
export const purchasesList = (
  reservationID: string,
  params?: PurchasesListParams,
) => {
  return nakupInstance<PurchasesList200>({
    url: `/reservations/${reservationID}/purchases`,
    method: "GET",
    params,
  });
};
/**
 * Create purchase
 * @summary Create purchase
 */
export const purchasesCreate = (
  reservationID: string,
  apiPurchaseRequestBody: ApiPurchaseRequestBody,
) => {
  return nakupInstance<ApiPurchaseResponse>({
    url: `/reservations/${reservationID}/purchases`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: apiPurchaseRequestBody,
  });
};
/**
 * Delete purchase
 * @summary Delete purchase
 */
export const purchasesDelete = (reservationID: string, purchaseID: string) => {
  return nakupInstance<void>({
    url: `/reservations/${reservationID}/purchases/${purchaseID}`,
    method: "DELETE",
  });
};
/**
 * Show purchase
 * @summary Show purchase
 */
export const purchasesShow = (reservationID: string, purchaseID: string) => {
  return nakupInstance<ApiPurchaseResponse>({
    url: `/reservations/${reservationID}/purchases/${purchaseID}`,
    method: "GET",
  });
};
/**
 * Update purchase
 * @summary Update purchase
 */
export const purchasesUpdate = (
  reservationID: string,
  purchaseID: string,
  apiPurchaseRequestBody: ApiPurchaseRequestBody,
) => {
  return nakupInstance<ApiPurchaseResponse>({
    url: `/reservations/${reservationID}/purchases/${purchaseID}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: apiPurchaseRequestBody,
  });
};
export type PurchasesListResult = NonNullable<
  Awaited<ReturnType<typeof purchasesList>>
>;
export type PurchasesCreateResult = NonNullable<
  Awaited<ReturnType<typeof purchasesCreate>>
>;
export type PurchasesDeleteResult = NonNullable<
  Awaited<ReturnType<typeof purchasesDelete>>
>;
export type PurchasesShowResult = NonNullable<
  Awaited<ReturnType<typeof purchasesShow>>
>;
export type PurchasesUpdateResult = NonNullable<
  Awaited<ReturnType<typeof purchasesUpdate>>
>;
