/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Nakup API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type {
  ApiReservationRequestBody,
  ApiReservationResponse,
  MyReservationsList200,
  MyReservationsListParams,
  ReservationsList200,
  ReservationsListParams,
} from ".././model";

import { nakupInstance } from "../../../lib/nakup-instance";

/**
 * List reservations
 * @summary List reservations
 */
export const reservationsList = (params?: ReservationsListParams) => {
  return nakupInstance<ReservationsList200>({
    url: `/reservations`,
    method: "GET",
    params,
  });
};
/**
 * Create reservation
 * @summary Create reservation
 */
export const reservationsCreate = (
  apiReservationRequestBody: ApiReservationRequestBody,
) => {
  return nakupInstance<ApiReservationResponse>({
    url: `/reservations`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: apiReservationRequestBody,
  });
};
/**
 * Delete reservation
 * @summary Delete reservation
 */
export const reservationsDelete = (reservationID: string) => {
  return nakupInstance<void>({
    url: `/reservations/${reservationID}`,
    method: "DELETE",
  });
};
/**
 * Show reservation
 * @summary Show reservation
 */
export const reservationsShow = (reservationID: string) => {
  return nakupInstance<ApiReservationResponse>({
    url: `/reservations/${reservationID}`,
    method: "GET",
  });
};
/**
 * Update reservation
 * @summary Update reservation
 */
export const reservationsUpdate = (
  reservationID: string,
  apiReservationRequestBody: ApiReservationRequestBody,
) => {
  return nakupInstance<ApiReservationResponse>({
    url: `/reservations/${reservationID}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: apiReservationRequestBody,
  });
};
/**
 * List reservations for the currently authenticated user
 * @summary List my reservations
 */
export const myReservationsList = (params?: MyReservationsListParams) => {
  return nakupInstance<MyReservationsList200>({
    url: `/reservations/my`,
    method: "GET",
    params,
  });
};
export type ReservationsListResult = NonNullable<
  Awaited<ReturnType<typeof reservationsList>>
>;
export type ReservationsCreateResult = NonNullable<
  Awaited<ReturnType<typeof reservationsCreate>>
>;
export type ReservationsDeleteResult = NonNullable<
  Awaited<ReturnType<typeof reservationsDelete>>
>;
export type ReservationsShowResult = NonNullable<
  Awaited<ReturnType<typeof reservationsShow>>
>;
export type ReservationsUpdateResult = NonNullable<
  Awaited<ReturnType<typeof reservationsUpdate>>
>;
export type MyReservationsListResult = NonNullable<
  Awaited<ReturnType<typeof myReservationsList>>
>;
