/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type {
  ApiMovieRequestBody,
  ApiMovieResponse,
  MoviesList200,
  MoviesListParams,
} from ".././model";

import { sporedInstance } from "../../../lib/spored-instance";

/**
 * List movies
 * @summary List movies
 */
export const moviesList = (params?: MoviesListParams) => {
  return sporedInstance<MoviesList200>({
    url: `/movies`,
    method: "GET",
    params,
  });
};
/**
 * Create movie
 * @summary Create movie
 */
export const moviesCreate = (apiMovieRequestBody: ApiMovieRequestBody) => {
  return sporedInstance<ApiMovieResponse>({
    url: `/movies`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: apiMovieRequestBody,
  });
};
/**
 * Delete movie
 * @summary Delete movie
 */
export const moviesDelete = (movieID: string) => {
  return sporedInstance<void>({ url: `/movies/${movieID}`, method: "DELETE" });
};
/**
 * Show movie
 * @summary Show movie
 */
export const moviesShow = (movieID: string) => {
  return sporedInstance<ApiMovieResponse>({
    url: `/movies/${movieID}`,
    method: "GET",
  });
};
/**
 * Update movie
 * @summary Update movie
 */
export const moviesUpdate = (
  movieID: string,
  apiMovieRequestBody: ApiMovieRequestBody,
) => {
  return sporedInstance<ApiMovieResponse>({
    url: `/movies/${movieID}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: apiMovieRequestBody,
  });
};
export type MoviesListResult = NonNullable<
  Awaited<ReturnType<typeof moviesList>>
>;
export type MoviesCreateResult = NonNullable<
  Awaited<ReturnType<typeof moviesCreate>>
>;
export type MoviesDeleteResult = NonNullable<
  Awaited<ReturnType<typeof moviesDelete>>
>;
export type MoviesShowResult = NonNullable<
  Awaited<ReturnType<typeof moviesShow>>
>;
export type MoviesUpdateResult = NonNullable<
  Awaited<ReturnType<typeof moviesUpdate>>
>;
