/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Spored API
 * API za upravljanje z kinodvoranami in njihovim sporedom
 * OpenAPI spec version: 1.0
 */
import type {
  ApiRoomRequestBody,
  ApiRoomResponse,
  RoomsList200,
  RoomsListParams,
} from ".././model";

import { sporedInstance } from "../../../lib/spored-instance";

/**
 * List rooms
 * @summary List rooms
 */
export const roomsList = (theaterID: string, params?: RoomsListParams) => {
  return sporedInstance<RoomsList200>({
    url: `/theaters/${theaterID}/rooms`,
    method: "GET",
    params,
  });
};
/**
 * Create room
 * @summary Create room
 */
export const roomsCreate = (
  theaterID: string,
  apiRoomRequestBody: ApiRoomRequestBody,
) => {
  return sporedInstance<ApiRoomResponse>({
    url: `/theaters/${theaterID}/rooms`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: apiRoomRequestBody,
  });
};
/**
 * Delete room
 * @summary Delete room
 */
export const roomsDelete = (theaterID: string, roomID: string) => {
  return sporedInstance<void>({
    url: `/theaters/${theaterID}/rooms/${roomID}`,
    method: "DELETE",
  });
};
/**
 * Show room
 * @summary Show room
 */
export const roomsShow = (theaterID: string, roomID: string) => {
  return sporedInstance<ApiRoomResponse>({
    url: `/theaters/${theaterID}/rooms/${roomID}`,
    method: "GET",
  });
};
/**
 * Update room
 * @summary Update room
 */
export const roomsUpdate = (
  theaterID: string,
  roomID: string,
  apiRoomRequestBody: ApiRoomRequestBody,
) => {
  return sporedInstance<ApiRoomResponse>({
    url: `/theaters/${theaterID}/rooms/${roomID}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: apiRoomRequestBody,
  });
};
export type RoomsListResult = NonNullable<
  Awaited<ReturnType<typeof roomsList>>
>;
export type RoomsCreateResult = NonNullable<
  Awaited<ReturnType<typeof roomsCreate>>
>;
export type RoomsDeleteResult = NonNullable<
  Awaited<ReturnType<typeof roomsDelete>>
>;
export type RoomsShowResult = NonNullable<
  Awaited<ReturnType<typeof roomsShow>>
>;
export type RoomsUpdateResult = NonNullable<
  Awaited<ReturnType<typeof roomsUpdate>>
>;
