/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication and authorization service for the PRPO project
 * OpenAPI spec version: 1.0
 */
import type {
  ApiAdminCreateUserRequest,
  ApiAdminUpdateUserRequest,
  ApiUserResponse,
  UsersList200,
  UsersListParams,
} from ".././model";

import { customInstance } from "../../../lib/axios-instance";

/**
 * List all users (admin endpoint)
 * @summary List users
 */
export const usersList = (params?: UsersListParams) => {
  return customInstance<UsersList200>({ url: `/users`, method: "GET", params });
};
/**
 * Create a new user with any role (admin only)
 * @summary Create user (admin)
 */
export const adminCreateUser = (
  apiAdminCreateUserRequest: ApiAdminCreateUserRequest,
) => {
  return customInstance<ApiUserResponse>({
    url: `/users`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: apiAdminCreateUserRequest,
  });
};
/**
 * Delete a specific user (admin endpoint)
 * @summary Delete user
 */
export const usersDelete = (userID: string) => {
  return customInstance<void>({ url: `/users/${userID}`, method: "DELETE" });
};
/**
 * Get a specific user by ID (admin endpoint)
 * @summary Get user by ID
 */
export const usersShow = (userID: string) => {
  return customInstance<ApiUserResponse>({
    url: `/users/${userID}`,
    method: "GET",
  });
};
/**
 * Update a specific user (admin endpoint)
 * @summary Update user
 */
export const usersUpdate = (
  userID: string,
  apiAdminUpdateUserRequest: ApiAdminUpdateUserRequest,
) => {
  return customInstance<ApiUserResponse>({
    url: `/users/${userID}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: apiAdminUpdateUserRequest,
  });
};
export type UsersListResult = NonNullable<
  Awaited<ReturnType<typeof usersList>>
>;
export type AdminCreateUserResult = NonNullable<
  Awaited<ReturnType<typeof adminCreateUser>>
>;
export type UsersDeleteResult = NonNullable<
  Awaited<ReturnType<typeof usersDelete>>
>;
export type UsersShowResult = NonNullable<
  Awaited<ReturnType<typeof usersShow>>
>;
export type UsersUpdateResult = NonNullable<
  Awaited<ReturnType<typeof usersUpdate>>
>;
